from typing import Tuple

from CharEncoded import CharEncoded

ALPHABET: Tuple[CharEncoded, ...] = (
    CharEncoded(roman="A", morse=".-"),
    CharEncoded(roman="B", morse="-..."),
    CharEncoded(roman="C", morse="-.-."),
    CharEncoded(roman="D", morse="-.."),
    CharEncoded(roman="E", morse="."),
    CharEncoded(roman="F", morse="..-."),
    CharEncoded(roman="G", morse="--."),
    CharEncoded(roman="H", morse="...."),
    CharEncoded(roman="I", morse=".."),
    CharEncoded(roman="J", morse=".---"),
    CharEncoded(roman="K", morse="-.-"),
    CharEncoded(roman="L", morse=".-.."),
    CharEncoded(roman="M", morse="--"),
    CharEncoded(roman="N", morse="-."),
    CharEncoded(roman="O", morse="---"),
    CharEncoded(roman="P", morse=".--."),
    CharEncoded(roman="Q", morse="--.-"),
    CharEncoded(roman="R", morse=".-."),
    CharEncoded(roman="S", morse="..."),
    CharEncoded(roman="T", morse="-"),
    CharEncoded(roman="U", morse="..-"),
    CharEncoded(roman="V", morse="...-"),
    CharEncoded(roman="W", morse=".--"),
    CharEncoded(roman="X", morse="-..-"),
    CharEncoded(roman="Y", morse="-.--"),
    CharEncoded(roman="Z", morse="--.."),

    CharEncoded(roman="0", morse="-----"),
    CharEncoded(roman="1", morse=".----"),
    CharEncoded(roman="2", morse="..---"),
    CharEncoded(roman="3", morse="...--"),
    CharEncoded(roman="4", morse="....-"),
    CharEncoded(roman="5", morse="....."),
    CharEncoded(roman="6", morse="-...."),
    CharEncoded(roman="7", morse="--..."),
    CharEncoded(roman="8", morse="---.."),
    CharEncoded(roman="9", morse="----."),

    CharEncoded(roman=".", morse=".-.-.-"),
    CharEncoded(roman=",", morse="--..--"),
    CharEncoded(roman="?", morse="..--.."),
    CharEncoded(roman="'", morse=".----."),
    CharEncoded(roman='"', morse=".-..-."),
    CharEncoded(roman="!", morse="-.-.--"),
    CharEncoded(roman="/", morse="-..-."),
    CharEncoded(roman="(", morse="-.--."),
    CharEncoded(roman=")", morse="-.--.-"),
    CharEncoded(roman="&", morse=".-..."),
    CharEncoded(roman=":", morse="---..."),
    CharEncoded(roman=";", morse="-.-.-."),
    CharEncoded(roman="=", morse="-...-"),
    CharEncoded(roman="+", morse=".-.-."),
    CharEncoded(roman="-", morse="-....-"),
    CharEncoded(roman="_", morse="..--.-"),
    CharEncoded(roman="$", morse="---..."),
    CharEncoded(roman="@", morse=".--.-."),
    CharEncoded(roman="¿", morse="..-.-"),
    CharEncoded(roman="¡", morse="--...-"),

)

SPECIAL_WORDS: Tuple[CharEncoded] = (CharEncoded(roman="ERROR...", morse="......"),)
