import chai from "chai";
import rectangleSentence from "../weekly-challenges/weekly-challenge-30.js";

const expect = chai.expect;

describe("rectangleSentence", function () {
  it("expect nothing to output, entering a empty", () => {
    const enteredSentence = "";
    const sortResult = rectangleSentence(enteredSentence);
    expect(sortResult).to.deep.equal("");
  });
  it("expect nothing to output, entering a space", () => {
    const enteredSentence = " ";
    const sortResult = rectangleSentence(enteredSentence);
    expect(sortResult).to.equal("");
  });
  it("expect nothing to output, entering a null", () => {
    const enteredSentence = null;
    const sortResult = rectangleSentence(enteredSentence);
    expect(sortResult).to.equal("");
  });

  it(`expect an array with its content between asterisks to output, entering a word "¿Qué te parece el reto?"`, () => {
    const enteredSentence = "¿Qué te parece el reto?";
    const sortResult = rectangleSentence(enteredSentence);
    const expectedResult = [
      "**********",
      "* ¿Qué   *",
      "* te     *",
      "* parece *",
      "* el     *",
      "* reto?  *",
      "**********",
    ];
    expect(sortResult).to.deep.equal(expectedResult);
  });

  it(`expect an array with its content between asterisks to output, entering a word "¿Pero bueno, que es esto? Anda que meterte en líos de estos con esta gente tan peligrosa..."`, () => {
    const enteredSentence =
      "¿Pero bueno, que es esto? Anda que meterte en líos de estos con esta gente tan peligrosa...";
    const sortResult = rectangleSentence(enteredSentence);
    const expectedResult = [
      "****************",
      "* ¿Pero        *",
      "* bueno,       *",
      "* que          *",
      "* es           *",
      "* esto?        *",
      "* Anda         *",
      "* que          *",
      "* meterte      *",
      "* en           *",
      "* líos         *",
      "* de           *",
      "* estos        *",
      "* con          *",
      "* esta         *",
      "* gente        *",
      "* tan          *",
      "* peligrosa... *",
      "****************",
    ];
    expect(sortResult).to.deep.equal(expectedResult);
  });
  it(`expect an array with its content between asterisks to output, entering a word "¿Pero bueno, que es esto? Anda que meterte en líos de estos con esta gente tan peligrosa... Supercalifragilisticoespialidoso"`, () => {
    const enteredSentence =
      "¿Pero bueno, que es esto? Anda que meterte en líos de estos con esta gente tan peligrosa... Supercalifragilisticoespialidoso";
    const sortResult = rectangleSentence(enteredSentence);
    const expectedResult = [
      "************************************",
      "* ¿Pero                            *",
      "* bueno,                           *",
      "* que                              *",
      "* es                               *",
      "* esto?                            *",
      "* Anda                             *",
      "* que                              *",
      "* meterte                          *",
      "* en                               *",
      "* líos                             *",
      "* de                               *",
      "* estos                            *",
      "* con                              *",
      "* esta                             *",
      "* gente                            *",
      "* tan                              *",
      "* peligrosa...                     *",
      "* Supercalifragilisticoespialidoso *",
      "************************************",
    ];
    expect(sortResult).to.deep.equal(expectedResult);
  });
  it(`expect an array with its content between asterisks to output, entering a long sentence`, () => {
    const enteredSentence =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum massa sit amet urna faucibus euismod. Fusce ullamcorper quam eu lectus ullamcorper molestie. Duis pretium augue id diam rhoncus hendrerit. Donec feugiat metus velit, eu volutpat lectus dignissim ac. Donec non enim accumsan, laoreet magna vel, dictum elit. Nullam faucibus sem eget faucibus dignissim. Aliquam luctus turpis sed urna maximus pulvinar. Aliquam eu elit non lacus sagittis venenatis in sit amet nulla. Mauris nunc sem, imperdiet ac augue sit amet, viverra viverra dui. Nunc facilisis fermentum neque, et tristique massa finibus hendrerit. Etiam non ex cursus sem tristique ultrices.Aliquam erat volutpat. Quisque finibus sagittis orci, sed vestibulum turpis porttitor nec. Phasellus ultricies nulla vel lacus molestie auctor. Duis vel tortor ut erat vehicula fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras pulvinar luctus luctus. Vestibulum condimentum nibh eget lorem lacinia, ut tempor sapien tincidunt. Sed eget ligula libero. Aenean in dictum nibh, rhoncus viverra nunc. In feugiat quis ligula feugiat tempus. Nullam a leo mi. Sed ut molestie erat. Praesent id orci et nulla mollis convallis id sed velit. Vivamus ullamcorper lorem massa, a iaculis mauris luctus quis.Sed vel imperdiet magna, eget semper sapien. Proin placerat elit nec aliquet ullamcorper. Sed feugiat augue ac ex aliquam, nec laoreet elit posuere. Duis ullamcorper metus sit amet orci tristique aliquam. Sed scelerisque lacus erat, vitae dapibus nisl gravida vel. Pellentesque a commodo felis, et volutpat ante. Vivamus auctor velit nec euismod elementum. Nullam euismod sapien non justo volutpat molestie. Suspendisse dolor tellus, ultricies porta dignissim nec, pellentesque a ipsum. Suspendisse potenti. Quisque lorem velit, imperdiet id ex eu, fringilla laoreet arcu. Aliquam orci magna, lacinia id arcu a, accumsan condimentum urna. Etiam vel gravida libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Nam non interdum diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras feugiat mi ligula, tincidunt fermentum velit posuere et. Quisque dignissim velit et massa rhoncus, vitae imperdiet mauris viverra. Donec eros purus, euismod quis tellus at, sollicitudin accumsan ante. Nunc quis ullamcorper purus. Nunc sed semper urna, non porttitor ante. Suspendisse elementum efficitur odio, eget euismod libero blandit ac. Ut ac efficitur leo. Etiam euismod tincidunt nunc ac vulputate. Ut placerat sollicitudin commodo.Sed eget urna non sem eleifend interdum in et dui. Vivamus ac elementum libero. Cras";
    const sortResult = rectangleSentence(enteredSentence);
    const expectedResult = [
      "********************",
      "* Lorem            *",
      "* ipsum            *",
      "* dolor            *",
      "* sit              *",
      "* amet,            *",
      "* consectetur      *",
      "* adipiscing       *",
      "* elit.            *",
      "* Donec            *",
      "* condimentum      *",
      "* massa            *",
      "* sit              *",
      "* amet             *",
      "* urna             *",
      "* faucibus         *",
      "* euismod.         *",
      "* Fusce            *",
      "* ullamcorper      *",
      "* quam             *",
      "* eu               *",
      "* lectus           *",
      "* ullamcorper      *",
      "* molestie.        *",
      "* Duis             *",
      "* pretium          *",
      "* augue            *",
      "* id               *",
      "* diam             *",
      "* rhoncus          *",
      "* hendrerit.       *",
      "* Donec            *",
      "* feugiat          *",
      "* metus            *",
      "* velit,           *",
      "* eu               *",
      "* volutpat         *",
      "* lectus           *",
      "* dignissim        *",
      "* ac.              *",
      "* Donec            *",
      "* non              *",
      "* enim             *",
      "* accumsan,        *",
      "* laoreet          *",
      "* magna            *",
      "* vel,             *",
      "* dictum           *",
      "* elit.            *",
      "* Nullam           *",
      "* faucibus         *",
      "* sem              *",
      "* eget             *",
      "* faucibus         *",
      "* dignissim.       *",
      "* Aliquam          *",
      "* luctus           *",
      "* turpis           *",
      "* sed              *",
      "* urna             *",
      "* maximus          *",
      "* pulvinar.        *",
      "* Aliquam          *",
      "* eu               *",
      "* elit             *",
      "* non              *",
      "* lacus            *",
      "* sagittis         *",
      "* venenatis        *",
      "* in               *",
      "* sit              *",
      "* amet             *",
      "* nulla.           *",
      "* Mauris           *",
      "* nunc             *",
      "* sem,             *",
      "* imperdiet        *",
      "* ac               *",
      "* augue            *",
      "* sit              *",
      "* amet,            *",
      "* viverra          *",
      "* viverra          *",
      "* dui.             *",
      "* Nunc             *",
      "* facilisis        *",
      "* fermentum        *",
      "* neque,           *",
      "* et               *",
      "* tristique        *",
      "* massa            *",
      "* finibus          *",
      "* hendrerit.       *",
      "* Etiam            *",
      "* non              *",
      "* ex               *",
      "* cursus           *",
      "* sem              *",
      "* tristique        *",
      "* ultrices.Aliquam *",
      "* erat             *",
      "* volutpat.        *",
      "* Quisque          *",
      "* finibus          *",
      "* sagittis         *",
      "* orci,            *",
      "* sed              *",
      "* vestibulum       *",
      "* turpis           *",
      "* porttitor        *",
      "* nec.             *",
      "* Phasellus        *",
      "* ultricies        *",
      "* nulla            *",
      "* vel              *",
      "* lacus            *",
      "* molestie         *",
      "* auctor.          *",
      "* Duis             *",
      "* vel              *",
      "* tortor           *",
      "* ut               *",
      "* erat             *",
      "* vehicula         *",
      "* fringilla.       *",
      "* Orci             *",
      "* varius           *",
      "* natoque          *",
      "* penatibus        *",
      "* et               *",
      "* magnis           *",
      "* dis              *",
      "* parturient       *",
      "* montes,          *",
      "* nascetur         *",
      "* ridiculus        *",
      "* mus.             *",
      "* Cras             *",
      "* pulvinar         *",
      "* luctus           *",
      "* luctus.          *",
      "* Vestibulum       *",
      "* condimentum      *",
      "* nibh             *",
      "* eget             *",
      "* lorem            *",
      "* lacinia,         *",
      "* ut               *",
      "* tempor           *",
      "* sapien           *",
      "* tincidunt.       *",
      "* Sed              *",
      "* eget             *",
      "* ligula           *",
      "* libero.          *",
      "* Aenean           *",
      "* in               *",
      "* dictum           *",
      "* nibh,            *",
      "* rhoncus          *",
      "* viverra          *",
      "* nunc.            *",
      "* In               *",
      "* feugiat          *",
      "* quis             *",
      "* ligula           *",
      "* feugiat          *",
      "* tempus.          *",
      "* Nullam           *",
      "* a                *",
      "* leo              *",
      "* mi.              *",
      "* Sed              *",
      "* ut               *",
      "* molestie         *",
      "* erat.            *",
      "* Praesent         *",
      "* id               *",
      "* orci             *",
      "* et               *",
      "* nulla            *",
      "* mollis           *",
      "* convallis        *",
      "* id               *",
      "* sed              *",
      "* velit.           *",
      "* Vivamus          *",
      "* ullamcorper      *",
      "* lorem            *",
      "* massa,           *",
      "* a                *",
      "* iaculis          *",
      "* mauris           *",
      "* luctus           *",
      "* quis.Sed         *",
      "* vel              *",
      "* imperdiet        *",
      "* magna,           *",
      "* eget             *",
      "* semper           *",
      "* sapien.          *",
      "* Proin            *",
      "* placerat         *",
      "* elit             *",
      "* nec              *",
      "* aliquet          *",
      "* ullamcorper.     *",
      "* Sed              *",
      "* feugiat          *",
      "* augue            *",
      "* ac               *",
      "* ex               *",
      "* aliquam,         *",
      "* nec              *",
      "* laoreet          *",
      "* elit             *",
      "* posuere.         *",
      "* Duis             *",
      "* ullamcorper      *",
      "* metus            *",
      "* sit              *",
      "* amet             *",
      "* orci             *",
      "* tristique        *",
      "* aliquam.         *",
      "* Sed              *",
      "* scelerisque      *",
      "* lacus            *",
      "* erat,            *",
      "* vitae            *",
      "* dapibus          *",
      "* nisl             *",
      "* gravida          *",
      "* vel.             *",
      "* Pellentesque     *",
      "* a                *",
      "* commodo          *",
      "* felis,           *",
      "* et               *",
      "* volutpat         *",
      "* ante.            *",
      "* Vivamus          *",
      "* auctor           *",
      "* velit            *",
      "* nec              *",
      "* euismod          *",
      "* elementum.       *",
      "* Nullam           *",
      "* euismod          *",
      "* sapien           *",
      "* non              *",
      "* justo            *",
      "* volutpat         *",
      "* molestie.        *",
      "* Suspendisse      *",
      "* dolor            *",
      "* tellus,          *",
      "* ultricies        *",
      "* porta            *",
      "* dignissim        *",
      "* nec,             *",
      "* pellentesque     *",
      "* a                *",
      "* ipsum.           *",
      "* Suspendisse      *",
      "* potenti.         *",
      "* Quisque          *",
      "* lorem            *",
      "* velit,           *",
      "* imperdiet        *",
      "* id               *",
      "* ex               *",
      "* eu,              *",
      "* fringilla        *",
      "* laoreet          *",
      "* arcu.            *",
      "* Aliquam          *",
      "* orci             *",
      "* magna,           *",
      "* lacinia          *",
      "* id               *",
      "* arcu             *",
      "* a,               *",
      "* accumsan         *",
      "* condimentum      *",
      "* urna.            *",
      "* Etiam            *",
      "* vel              *",
      "* gravida          *",
      "* libero.          *",
      "* Pellentesque     *",
      "* habitant         *",
      "* morbi            *",
      "* tristique        *",
      "* senectus         *",
      "* et               *",
      "* netus            *",
      "* et               *",
      "* malesuada        *",
      "* fames            *",
      "* ac               *",
      "* turpis           *",
      "* egestas.Nam      *",
      "* non              *",
      "* interdum         *",
      "* diam.            *",
      "* Vestibulum       *",
      "* ante             *",
      "* ipsum            *",
      "* primis           *",
      "* in               *",
      "* faucibus         *",
      "* orci             *",
      "* luctus           *",
      "* et               *",
      "* ultrices         *",
      "* posuere          *",
      "* cubilia          *",
      "* curae;           *",
      "* Class            *",
      "* aptent           *",
      "* taciti           *",
      "* sociosqu         *",
      "* ad               *",
      "* litora           *",
      "* torquent         *",
      "* per              *",
      "* conubia          *",
      "* nostra,          *",
      "* per              *",
      "* inceptos         *",
      "* himenaeos.       *",
      "* Cras             *",
      "* feugiat          *",
      "* mi               *",
      "* ligula,          *",
      "* tincidunt        *",
      "* fermentum        *",
      "* velit            *",
      "* posuere          *",
      "* et.              *",
      "* Quisque          *",
      "* dignissim        *",
      "* velit            *",
      "* et               *",
      "* massa            *",
      "* rhoncus,         *",
      "* vitae            *",
      "* imperdiet        *",
      "* mauris           *",
      "* viverra.         *",
      "* Donec            *",
      "* eros             *",
      "* purus,           *",
      "* euismod          *",
      "* quis             *",
      "* tellus           *",
      "* at,              *",
      "* sollicitudin     *",
      "* accumsan         *",
      "* ante.            *",
      "* Nunc             *",
      "* quis             *",
      "* ullamcorper      *",
      "* purus.           *",
      "* Nunc             *",
      "* sed              *",
      "* semper           *",
      "* urna,            *",
      "* non              *",
      "* porttitor        *",
      "* ante.            *",
      "* Suspendisse      *",
      "* elementum        *",
      "* efficitur        *",
      "* odio,            *",
      "* eget             *",
      "* euismod          *",
      "* libero           *",
      "* blandit          *",
      "* ac.              *",
      "* Ut               *",
      "* ac               *",
      "* efficitur        *",
      "* leo.             *",
      "* Etiam            *",
      "* euismod          *",
      "* tincidunt        *",
      "* nunc             *",
      "* ac               *",
      "* vulputate.       *",
      "* Ut               *",
      "* placerat         *",
      "* sollicitudin     *",
      "* commodo.Sed      *",
      "* eget             *",
      "* urna             *",
      "* non              *",
      "* sem              *",
      "* eleifend         *",
      "* interdum         *",
      "* in               *",
      "* et               *",
      "* dui.             *",
      "* Vivamus          *",
      "* ac               *",
      "* elementum        *",
      "* libero.          *",
      "* Cras             *",
      "********************",
    ];
    expect(sortResult).to.deep.equal(expectedResult);
  });
});
